sudo: required

language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
- chmod +x grainw

install:
- ./grainw generate || echo 'hide exit code'

before_script:
- eval "$(ssh-agent -s)"
- chmod 600 .ssh/git_private_key.ppk
- ssh-add .ssh/git_private_key.ppk

script:
- ./grainw deploy
