sudo: required

language: java

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.grain/packages/"
  - "$HOME/.grain/tools/"

before_install:
- mkdir -p .travis
- openssl aes-256-cbc -K $encrypted_55f98c6c891f_key -iv $encrypted_55f98c6c891f_iv
  -in id_rsa.enc -out .travis/id_rsa -d
- chmod +x gradlew
- chmod +x grainw

install:
- "./grainw generate || echo 'hide exit code'"

before_script:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/id_rsa
- ssh-add .travis/id_rsa
- git config --global user.email "yermilov17@gmail.com"
- git config --global user.name "Travis-CI"

script:
- "./grainw deploy"

env:
  global:
  - secure: b84t7UGOP53niXRctdTvmOeUWFyrhagTfDcdsszyzBLtXdOb/ja1wv0WXln2KEiZEFRsOtixKxRzuWcFJtgXVBHmRKScuMZiwm63oPMjKLHyeVy1LQUTPTTjSOEOdJxSyATDLkqvhjhm/bn7TWa06Tjoy06Li6abpZF6KuyVDt874VR4Wa2sn20D1067ahtR5DZFcsCIGNIAiQOXyV7SwOOrLU84nMG4oOOpk7kpCjFSoTf/ssOjD6yti/9ffQW0JMwGKACHOq8HvL3addxrNYXZLaJJOdzR0NxeEmB8s7RwsfWsQyf/RttfQRulxfNHRduRO9wu7bFW5MpHk9+wmX2wXHbam4BkRz5nn9UUww+DMUu5p/uzpn1S8+NHmhU00RbYsgdkp9PcGDSSxKYYkeoI9mCGrw4Rfg267MAvofxRxXkFruxTibErFIM0HdKs/4wxZO06sVJ1avznyK8vwIvqgbpoFl2vmxcDCVoQriTRXE8SjhH4XnO25tVToB/mXjxfJ9g9NHT8sETWmTHjLKnEtzmejWRKSH3ic0PwUFSXINXjP1e+pZP07/QyAN3f0JkhZrqbtaaHYnaC8EX31xVW9Uwa45m+BdODmEn7IurPgRyKMbSyyNkF8Fub//zs4fYzyvO1ZAe5spYYuSpHYMjSb3B7pWHkYutaOuzopKE=
  - secure: SZ/aa9OfDPsb38gKq6MBYnLUgEKhvcovQMdmmyL70BKBq9Ciy9siZ5aYPHL/HrC1Szm5Jo21mRat+gLT4HQqefaKcv0dXUw0wIyp+5YFcUcy1UAOOw/F3/IRV4tJsDr1kzGZ5N77k9XoC0OsyGu3OjBAl0xa4w0GvpEYyaUlKhyI6no3kxGZOTVhyy1O0OQ55/F6oIn4u1/fBIHA9K22kcpdWBSkc70G165nS+tBeZCASIgrD/2HvakiRUKhKKoSmm8TxNQqhsQt8YaLYdMiy87GDHU+WrPv+UCXCAJ1JjJ51wpSZG7juu7I7qAgRIVVD0usjFiAwOXzSUuSb+aoj2zCYVfO3FFwGKM6KLfrz6otjJ2ZO006WlhiY9PWacDLJprYUgqxbvz+Z8AT/iTwr1X8rjJrUMtJNhCOpF61s4stJETKqudBw/v+4L16R9Uv30y1hnTZZqU0z6ibc46DDA1tOTurHY6domN4R82vuIgzaqguDuLDK/5LE9UzxN1JPJGG0X0/aQnPj64pXFfHuBs8fpD0s3fJIRWGnhsJmiBB2sQcZLhSyi5Lf39CsXlmA6pOGcXCDFbjnGx7WMMj95oen1M3RcwQy47tLuKTaiiL4y1fhLI39fpSEAynA7kZencs5cufAm7JlDc7XZoS8A4BJFEi5ROQFjlOYRGfV2U=
  - secure: WCQBFQTDxJThMph49hTl04CTlfvjAxEgrLiNFTtp3doxb/WlXhUrzcAWSv87fr0+iqyJv4sKWAiUt6sU6r5RnLyJvV0afy8GTngIbnUXdxQDzVzsVB7qiaD9c8DXHdjRqYsdRhVWBdR67efUikR807SUTWE6Sz0mfRZNqqeOPC5KZ8QHNnrADPkQI4YOecQ+NcmfLvBhOG3ntGaingFdEq4haMX34F39eiP+hPo0sfVbT/h42p8QjKN2XumoO1jDTw/72fPQww+58Vu+SP7dTJJawsnno8LTsu1ywUuEnCYNzBy+0f1Vdkfjaoyokdvrok5SRGaxImUrIiWOFScHWoXTGdKs3P9+2aSm4zlJSsTjkiNkPQ3bo1d/Js8/C+oTHqr5PzCWHKAUoqgsV9J829faX7sMHG9TGwWgnkAN4k7690uNjUELnYphRwZSMGPo/4BQ4B/iC3gOYR3AMaBk3WWT/RYfE9t4C37J+u7uHsikL19fnqoM5Q5Ayz+JilrUO004qhnygXA6H6ieeEMw0vAzf3GK9Bdr9PMpih60TltzVimFaC4/fmZzjGfyZOgdk0YhuQEb3vi5u1xWcPIR6wJkuyg/ywNCUC9j92tfIO6zcrdM+fuRqe1f3SAKaPjKtZKTw54RG5s6N5g7kDTri/BUZD2FD5kpw3BkHF0V10A=
  - secure: G+Ccb+cy+uxeyKRzuAPtCHjcE0NN41O8dTwxf65NYsBSlzJSIQ+BwjZPG5nHdtp2vONyFZ7mWO84AOpXWK0yJHEk4A5JRnOTBjl4JcC53dIyBc99yx6rqkt8TgQUppuAPBe/l+HCLNsFv8Ch83Qwpt3Zn4cHU+kK7EqSqI3hrfGl9h1zGMUpaUJHxGK17UnpRCPoxz6Ey6ujFXzGQpKG9XFGjiXTe3teZMnVqQ7bMnKfoD1qMnpV0EtpPuSmlmZku5rJgMnVxJLCGs4rqu3qN8HfQ0y7JuQnFu2Z1wcuX6Ir8R5faE2lSeNfNjitvhTGuSdnCegKSe/epNn3l7Ez6wkKeWzDBe3nsna2qQDvyhgHzkmKwOltxeRTnN4jBjiW/Lm5MxGaugVS3/ku63q+1MCy42RdEeLEa73O03+j6/FcFfBiIYowhkm3jD2nSEkqo3IGRrKLQrtm36otCT6tsoILJcmmIGJRDenBHqucYzK0nFJDictSh7cRCU1gjozk5IOLtR18+bleDe1zjo8phmZAzwP3qBX2n9hqhUWSKiVdB2PBDbUyo5g6wuA0PLsakt1OCr6SKlWO7PjjGiNTGF0Kv+oSptWgf3czhiV97bOdDPl5cmChq4r3h9871DNRoOOfaEvOgqc4Z4wJ1b4ya8QH6qv2dXGroahSJIw2diI=
