language: java

before_install:
- mkdir -p .travis
- openssl aes-256-cbc -K $encrypted_55f98c6c891f_key -iv $encrypted_55f98c6c891f_iv -in id_rsa.enc -out .travis/id_rsa -d
- chmod +x gradlew
- chmod +x grainw

install:
- "./grainw generate"

before_script:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/id_rsa
- ssh-add .travis/id_rsa
- git config --global user.email "yermilov17@gmail.com"
- git config --global user.name "Travis-CI"

script:
- "./grainw deploy"
