---
layout: post
title: "Groovy static sites with Grain"
date: "2017-03-20 14:57"
updated: "2017-03-20 14:57"
categories: [grain, groovy, asciidoctor, github pages, static sites]
comments: true
published: false
sharing: true
---
:linkattrs:

First option I considered when I decided to start up this blog was to use static site generator and Jekyll as the most popular one was an obvious option.
Recently after I was ready with the first version of this blog and first post - link:${r '/blog/2017-02-20-jekyll-githubpages-asciidoc.adoc'}['Using Jekyll, Asciidoctor and GitHub Pages for static site creation', window="_blank"], I've noticed a link in link:https://twitter.com/sdelamo[@sdelamo, window="_blank"] link:http://groovycalamari.com/issues/68[Groovy Calamary #68, window="_blank"] to the static site generator from Groovy world - link:https://sysgears.com/grain/[Grain, window="_blank"].
As I consider myself as a huge Groovy ecosystem fan, I could not resist it and quickly migrated this blog to Grain.

++++
<!--more-->
++++

== Why static matters?

Typical web resource after you request a page from it, does something like following:

. fetch some data from storage
. process it
. select one of web page templates and render it
. return result

Many of them do not require dedicated data storage or data itself is changing relatively rarely.
It means that web pages can be generated once and served without no additional processing for every request.

It's very important that we should not return to the boring Web 1.0 world.
If client state on your site is not persisted, it can be handled by JavaScript locally.
If content is changing relatively rarely, you can just redeploy it with every change.
If you need something like commenting feature, you can rely on external resources (for example link:https://disqus.com[disqus.com, window="_blank"] in this case).

And if you get rid of all heavy dynamic weapons like databases and server-side code and express your site as a collection of HMTL, CSS and JavaScript files you can gain some very worthy benefits: ease of site deployment, content caching and delivering (which leads to better performance) and security management.

== Service site generators

Typical static site generator takes your content (it can be plain text file, markdown, asciidoc, etc.) along with the desired layout (usually HTML with some kind of template DSL) and transform them into a collection of HTML, CSS and JavaScript files ready for deployment and servicing as a static web resource.
According to link:https://www.staticgen.com/[staticgen.com, window="_blank"], there are dozens of different static sites generators and link:https://jekyllrb.com[Jekyll, window="_blank"] is the most popular from them.
I've already posted an link:${r '/blog/2017-02-20-jekyll-githubpages-asciidoc.adoc'}[article, window="_blank"] about Jekyll, and today we will look closely at link:https://sysgears.com/grain/[Grain, window="_blank"], which is actually a workhorse of this blog itself.

== Links

link:https://www.staticgen.com/[Top Open-Source Static Site Generators, window="_blank"]

link:https://jekyllrb.com[Jekyll's home, window="_blank"]

link:${r '/blog/2017-02-20-jekyll-githubpages-asciidoc.adoc'}['Using Jekyll, Asciidoctor and GitHub Pages for static site creation', window="_blank"]

link:https://sysgears.com/grain/[Grain's home, window="_blank"]
